export const ACTIONS = {
  SET_API_RES: 'SET_API_RES',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_EMAIL: 'SET_EMAIL',
  SET_PASSWORD: 'SET_PASSWORD',
  SET_DONE: 'SET_DONE',
  SET_ARRAY_OF_EXERCISES: 'SET_ARRAY_OF_EXERCISES',
  SET_STATUS_TIMER: 'SET_STATUS_TIMER',
  SET_SAGA: 'SET_SAGA',
  SET_EXERCISE: 'SET_EXERCISE',
  SET_STRETCHING: 'SET_STRETCHING',
  SET_WARM_UP: 'SET_WARM_UP',
  SET_INDEX_ITEM: 'SET_INDEX_ITEM',
  SET_SECONDS: 'SET_SECONDS',
  SET_GET_READY: 'SET_GET_READY'
};
