export const ACTIONS = {
  SET_API_RES: 'SET_API_RES',
  SET_ARRAY_OF_EXERCISES: 'SET_ARRAY_OF_EXERCISES',
  SET_SECONDS_EXERSICES: 'SET_SECONDS_EXERSICES',
  SET_SECONDS_WARM_UP: 'SET_SECONDS_WARM_UP',
  SET_SECONDS_STRETCHING: 'SET_SECONDS_STRETCHING',
  SET_STATUS_TIMER: 'SET_STATUS_TIMER',
  SET_SAGA: 'SET_SAGA',
  SET_EXERCISE: 'SET_EXERCISE',
  SET_STRETCHING: 'SET_STRETCHING',
  SET_WARM_UP: 'SET_WARM_UP',
  SET_INDEX_ITEM: 'SET_INDEX_ITEM',
  SET_SECONDS: 'SET_SECONDS',
  SET_GET_READY: 'SET_GET_READY'
};
