export const ACTIONS = {
  SET_NEW_HEADER: 'SET_NEW_HEADER',
  SET_NEW_DATE: 'SET_NEW_DATE',
  SET_NEW_TODO: 'SET_NEW_TODO',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_DATE: 'SET_DATE',
  SET_VALUE: 'SET_VALUE',
  SET_ARRTODO: 'SET_ARRTODO',
  SET_MONTH: 'SET_MONTH',
  SET_PASSWORD: 'SET_PASSWORD',
  SET_EMAIL: 'SET_EMAIL'
};
